server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:orderdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

resilience4j:
  retry:
    instances:
      restaurantServiceRetry:
        max-attempts: 3
        wait-duration: 500ms
        retry-exceptions:
          - feign.FeignException
  circuitbreaker:
    instances:
      restaurantServiceCB:
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 2